#!/bin/bash

# source Default - Settings from /etc/default/clone-settings
. /etc/default/clone-settings

# Sleep until System has configured Resolutions
sleep $SLEEP_TIME

# Find 1. Screen
SCREEN1=$(xrandr --query | awk '/ connected /{ print $1 }' | head -1)
#echo $SCREEN1

# Find 2. Screen
SCREEN2=$(xrandr --query | awk '/ connected /{ print $1 }' | tail -1)
#echo $SCREEN2

# Set Resolution
if [ $RESOLUTION = "0x0" ];
then
	# Find Maximum Resolution in Screen 1 & Screen 2
	RESOLUTION=$(xrandr --query | awk '/^ *[0-9]*x[0-9]*/{ print $1 }' | sort -g -r | uniq -d | head -1)
	#echo $RESOLUTION

fi

# Set Clone Modus with Maximum Resolution 
xrandr --output $SCREEN1 --mode $RESOLUTION --output $SCREEN2 --mode $RESOLUTION --same-as $SCREEN1
