#!/bin/bash

#if [ $(whoami)="user" ];
#then
#  echo "Geben sie bitte Ihren Benutzernamen ein."
#  read LOGINNAME
#else
#  LOGINNAME=$(whoami)
#fi

echo "Geben sie bitte Ihren Benutzernamen ein."
read LOGINNAME
smbpasswd -r smb01 -U $LOGINNAME